### ISSUE TITLE
Не хранить данные подключения в коде

### ISSUE THREAD

**Issue by los-romka** [PowerSl1d3/CXXRestFullAPI#1]
https://github.com/PowerSl1d3/CXXRestFullAPI/blob/ac6c7cdbfde188391b46a4ec5f818ca77ac04fad/lib/connection.cpp#L9

Считается антипаттерном такое в коде хранить. Обычно выносят в ENV (переменные окружения).

**Comment by PowerSl1d3** [comment]
Допилено, вынес во внешний файл sql.cfg.
