### ISSUE TITLE
Убрать возможность делать SQL-инъекцию

### ISSUE THREAD

**Issue by los-romka** [PowerSl1d3/CXXRestFullAPI#2]
https://github.com/PowerSl1d3/CXXRestFullAPI/blob/ac6c7cdbfde188391b46a4ec5f818ca77ac04fad/lib/taskDataBase.cpp#L20

В коде используется обычная конкатенация со строкой, что позволяет злоумышленнику провести SQL-инъекцию (https://ru.wikipedia.org/wiki/%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_SQL-%D0%BA%D0%BE%D0%B4%D0%B0) 

Рекомендуется использовать биндинг параметров (оно же подготовленного выражение): https://dev.mysql.com/doc/connector-cpp/1.1/en/connector-cpp-examples-prepared-statements.html

**Comment by PowerSl1d3** [comment]
Отлично, это тоже переделал
